name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        options: >-
          --env POSTGRES_USER=postgres
          --env POSTGRES_PASSWORD=postgrespostgres
          --env POSTGRES_DB=postgres
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:6
        ports:
          - 6379:6379

      zookeeper:
        image: bitnami/zookeeper:latest
        options: --env ALLOW_ANONYMOUS_LOGIN=yes
        ports:
          - 2181:2181

      kafka:
        image: bitnami/kafka:latest
        options: >-
          --env ALLOW_PLAINTEXT_LISTENER=yes
          --env KAFKA_BROKER_ID=1
          --env KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
          --env KAFKA_LISTENERS=PLAINTEXT://:9092
          --env KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
          --env KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        ports:
          - 9092:9092

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: |
          # Add your test commands here
          echo "Running tests"

      - name: Tear down
        run: docker-compose -f docker-compose.yml down
